import { paths, components } from "./generated-api-v2.d.ts"; // <- generated by openapi-typescript

// Schema Obj
type OrderType = components["schemas"]["Order"];

// Path params
type EndpointParams = paths["/store/order"]["parameters"];

// Request obj
type RequestParams = paths["/store/order"]["post"]["requestBody"]["content"]["application/json"]["schema"];

// Response obj
type SuccessResponse = paths["/store/order"]["post"]["responses"][200]["content"]["application/json"]["schema"];
type ErrorResponse = paths["/store/order"]["post"]["responses"][500]["content"]["application/json"]["schema"];